- name: Init Kube Cluster
  hosts: masters
  become: true
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --control-plane-endpoint=10.20.20.10 --pod-network-cidr=192.168.0.0/16 --upload-certs
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy kubeconfig
      shell: |
                mkdir -p $HOME/.kube
                sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
                sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: install Pod network
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      args:
        chdir: $HOME

    - name: Get the token for joining the worker nodes
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/root/ansible/kubernetes/files/kubernetes_join_command" mode=0777
